### ISSUE TITLE
Don't force usage of roles via grains

### ISSUE THREAD

**Issue by samos123** [saltstack-formulas/hadoop-formula#10]
I may be misunderstanding saltstack usage. Here is my case: I don't want to specify roles via grains and instead would like to use nodegroups, pillars and/or states to define which nodes get installed which services / components of hadoop

Quick example, I would to be able to have a top.sls which contains:
```
base:
  'datanode-*':
    - hadoop.hdfs.slave # or use hadoop.hdfs.datanode

  'namenode-*':
    - hadoop.hdfs.master # or use hadoop.hdfs.namenode hope you get the idea
```

**Comment by lextoumbourou** [comment]
The flexible targeting code seems to be working quite well for us. Would love to see it in master.

**Comment by samos123** [comment]
Ok will try to update code based on review of Steffen next week so that it
can get merged.

**Comment by sroegner** [comment]
Thanks a lot guys - a little more testing was exactly what i had wanted to see before the merge and generally the idea seems to work quite well.

**Comment by benhosmer** [comment]
@sroegner What are your thoughts on having an `hadoop.hdfs_master` and `hadoop.hdfs_slave` instead?

**Comment by sroegner** [comment]
@benhosmer I'm open to (and have been thinking about) that sort of change but we'd need to go all the way and do the same at least for yarn rm and nm. At the same time (since this is a potentially breaking change) it should also allow for configuration of Namenode or Resourcemanager HA (where you end up with standby masters). Feel like trying that out in a branch?

**Comment by sroegner** [comment]
To everybody: if there are no objections i'd like to go forward and merge the _flexible_targeting_no_role_forcing_ branch into master tonight - i did some more testing and think we should treat any regressions as such in master.

**Comment by benhosmer** [comment]
Yes. I had difficulty testing this out on a single vagrant machine. I'll
also see what I can do about splitting them up.

**Comment by sroegner** [comment]
@benhosmer please feel free to open a new issue - there should be no problems running single-instance vagrant boxes. Let me know how i can be of help.
