### ISSUE TITLE
/var/run/hadoop does not survive reboot causing service states to fail (Debian)

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/hadoop-formula#28]
I'd like to verify this behavior in a RedHat based distro. I'll check myself if no one comments.

Init scripts usually manage creating a directory in `/var/run` upon start/restart [(Source)](http://askubuntu.com/questions/303120/how-folders-created-in-var-run-on-each-reboot). Can this be done here?

**Comment by sroegner** [comment]
I suppose PR #33  fixed this.

**Comment by gravyboat** [comment]
@blbradley Can you please test this and if it doesn't open the issue back up?

**Comment by blbradley** [comment]
Yes it did!

Whew, what a delay on my response.
