### ISSUE TITLE
HDP source urls

### ISSUE THREAD

**Issue by variia** [saltstack-formulas/hadoop-formula#36]
Hi,

Just curious where you got the hdp tarball urls from. I am trying to update the formula as I would like to use the latest hdp 2.3.4 which features spark 1.5.2.

All I can find is RPM refs...

Thanks,
Ivan

**Comment by sroegner** [comment]
As you noticed these are not advertised anywhere but as soon as you have the build number (from the RPM for example) you can normally piece them together following the existing ones.

**Comment by gravyboat** [comment]
I'm going to close this since the PR is merged that addresses this.

**Comment by variia** [comment]
Awesome, thanks guys.
