### ISSUE TITLE
YARN data disk configuration

### ISSUE THREAD

**Issue by certain-ops** [saltstack-formulas/hadoop-formula#52]
@sroegner, what is the reason that YARN data disks are configurable only through grains? It seems like something one may want to configure globally. 

thx!

**Comment by sroegner** [comment]
@certain-ops we run the formula atop different hardware - even mixing machines with a different number of data disks is frequent. Putting disk config into a grain at bare-metal provisioning time is the best solution there. That is not to say that there shouldn't be also a way to do this via pillar/globally but apparently nobody has had enough of a pressing need so far.

**Comment by certain-ops** [comment]
@sroegner, got it. We do most configuration through pillar and hostname convention, so I may end up submitting a PR in the future to address this. But for now, I've just forked this formula. Thanks!
